In [3]:
!pip install xlrd
import pandas as pd
import numpy as np

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.5/96.5 kB 3.2 MB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

# Age Percentage

In [52]:
import os
csv_folder = '../00_source_data/age_percentage'
csv_files = [os.path.join(csv_folder, file) for file in os.listdir(csv_folder) if file.endswith('.csv')]

In [85]:
combined_age_pct = pd.concat([pd.read_csv(file, index_col=0,header=2, skiprows=[3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69]) \
    for file in csv_files])

# drop the last two columns
combined_age_pct = combined_age_pct.iloc[:, :-2]

# create the column for year
combined_age_pct['year'] = np.repeat(np.arange(2008, 2022), 51)

# make sure col/row number is correct
assert combined_age_pct.shape[0] == 51*14
assert combined_age_pct.shape[1] == 7

combined_age_pct

,Children 0-18,Adults 19-25,Adults 26-34,Adults 35-54,Adults 55-64,65+,year
Location,,,,,,,
Alabama,0.237,0.087,0.115,0.251,0.135,0.175,2008
Alaska,0.259,0.093,0.139,0.246,0.132,0.130,2008
Arizona,0.240,0.093,0.121,0.241,0.124,0.182,2008
Arkansas,0.247,0.087,0.115,0.248,0.131,0.173,2008
California,0.237,0.092,0.137,0.263,0.123,0.149,2008
...,...,...,...,...,...,...,...
Virginia,0.234,0.083,0.119,0.264,0.134,0.167,2021
Washington,0.228,0.082,0.136,0.265,0.126,0.163,2021
West Virginia,0.212,0.083,0.101,0.252,0.143,0.209,2021
Wisconsin,0.228,0.085,0.114,0.249,0.144,0.179,2021
Wyoming,0.240,0.085,0.104,0.258,0.132,0.181,2021

# EST Homelessness

In [86]:
csv_folder = '../00_source_data/Estimates_of_Homelessness'
csv_files = [os.path.join(csv_folder, file) for file in os.listdir(csv_folder) if file.endswith('.csv')]

In [101]:
combined_homelessness = pd.concat([pd.read_csv(file, index_col=0,header=2, \
    skiprows=[3,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77]) \
    for file in csv_files])

# select the column we need
combined_homelessness = combined_homelessness.loc[:,['Total People Experiencing Homelessness']]

# create the column for year
combined_homelessness['year'] = np.repeat(np.arange(2007, 2021), 51)

# make sure col/row number is correct
assert combined_homelessness.shape[0] == 51*14
assert combined_homelessness.shape[1] == 2

combined_homelessness

               Total People Experiencing Homelessness  year
Location
Alabama                                          5452  2007
Alaska                                           1642  2007
Arizona                                         14646  2007
Arkansas                                         3836  2007
California                                     138986  2007
...                                               ...   ...
Virginia                                         1214  2020
Washington                                      22782  2020
West Virginia                                    6525  2020
Wisconsin                                        1667  2020
Wyoming                                           515  2020

[714 rows x 2 columns]

# GDP

In [105]:
gdp = pd.read_csv('../00_source_data/gdp/AZNGSP.csv', header=0)
gdp

          DATE    AZNGSP
0   1997-01-01  132281.0
1   1998-01-01  143302.6
2   1999-01-01  155755.8
3   2000-01-01  165110.7
4   2001-01-01  171909.6
5   2002-01-01  180522.3
6   2003-01-01  193634.9
7   2004-01-01  206541.1
8   2005-01-01  227915.9
9   2006-01-01  245957.0
10  2007-01-01  261392.0
11  2008-01-01  262926.0
12  2009-01-01  246424.3
13  2010-01-01  251153.0
14  2011-01-01  260915.7
15  2012-01-01  271440.0
16  2013-01-01  278591.6
17  2014-01-01  287666.6
18  2015-01-01  299393.3
19  2016-01-01  313081.4
20  2017-01-01  332001.8
21  2018-01-01  351879.5
22  2019-01-01  372393.5
23  2020-01-01  382072.3
24  2021-01-01  420026.7
25  2022-01-01  458949.8

## Income Equality

In [21]:
income_inequality = pd.read_excel('../00_source_data/h08_Income_Inequality.xls', index_col=0, header=4)

In [51]:
# only get even columns
income_inequality2 = income_inequality.iloc[2:53, 0::2]
income_inequality2.drop(['2017 (40)','2013 (39)'], axis=1, inplace=True)

# rename columns, get the first 4 digits of the column name
income_inequality2.columns = [int(str(col)[:4]) for col in income_inequality2.columns]
income_inequality2

,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,...,1993,1992,1991,1990,1989,1988,1987,1986,1985,1984
State,,,,,,,,,,,,,,,,,,,,,
Alabama,49936,51113,47221,44509,42278,41381,43464,42590,40933,39980,...,25082,25808,24346,23357,21284,19948,19734,19132,18333,17310
Alaska,68734,72231,75723,75112,67629,61137,63648,57431,57848,61604,...,42931,41802,40612,39298,36006,33103,33233,31356,34782,32356
Arizona,62283,61125,57100,52248,49254,50602,47044,48621,46896,45739,...,30510,29358,30737,29224,28552,26435,26749,25500,23877,21425
Arkansas,49781,48829,45907,42798,44922,39919,39018,41302,38587,36538,...,23039,23882,23435,22786,21433,20172,18827,18730,17451,15674
California,70489,69759,66637,63636,60487,57528,57020,53367,54283,56134,...,34073,34903,33664,33290,33009,30287,30146,29010,26981,25287
Colorado,73034,74172,70566,66596,60940,63371,57255,58629,60233,55930,...,34488,32484,31499,30733,26806,26214,26476,27192,28182,25801
Connecticut,72812,72780,75923,72889,70161,67781,64247,65415,65998,64851,...,39516,40841,42154,38870,42321,36213,32862,32721,31090,29951
Delaware,65012,62318,58046,57756,57522,52219,48972,54660,55214,52114,...,36064,35678,32585,30804,32068,30505,29244,25626,22980,25819
D.C.,85750,83382,70982,70071,68277,60675,65246,55251,56928,53141,...,27304,30247,29885,27392,26752,26741,27455,24322,21076,20408
Florida,54644,53681,51176,48825,46140,47886,46071,45105,44066,45631,...,28550,27349,27252,26685,26085,25406,24489,22849,21343,19785
Georgia,55821,57016,53527,50768,49555,47439,48121,45973,44117,43340,...,31663,28797,27212,27561,27542,26566,26714,24370,21049,19984
Hawaii,80108,73575,72133,64514,71223,61408,56263,59047,59539,55649,...,42662,42113,37246,38921,35035,33024,35022,29003,28961,28877
Idaho,58728,60208,56564,51624,53438,51767,47922,47459,47050,46778,...,31010,27704,26116,25305,24654,23450,20755,20749,20761,21092
Illinois,70145,64609,61386,60413,54916,57196,51738,50637,50728,52870,...,32857,31551,31884,32542,31300,29524,27084,26511,24870,23752
Indiana,59892,58873,56094,51983,48060,50553,46158,44445,46139,44305,...,29475,28530,27089,26928,25898,26293,22519,22728,22675,22770
Iowa,68718,63481,59094,60855,57810,54855,53442,50219,49016,50721,...,28663,28743,28553,27288,26265,24305,22190,22459,20927,19863
Kansas,63938,57872,56810,54865,53444,51485,50003,46147,46054,44717,...,29770,30346,29295,29917,26862,25566,25583,23926,22788,24629
Kentucky,54555,51348,45369,42387,42786,42158,41086,39856,41104,42664,...,24376,23485,23764,24780,23283,19907,20673,19874,17361,17680
Louisiana,49973,43903,42196,45922,42406,39622,39085,40658,39300,45433,...,26312,25439,25299,22405,22861,20497,21349,20890,21179,18949
Maine,58663,51664,50856,50756,51710,50121,49158,49693,47931,47502,...,27438,29617,27868,27464,28221,26402,23600,23424,20519,20648
Maryland,86223,81084,73760,73594,76165,65262,71836,68876,64201,64186,...,39939,37203,36952,38857,36016,36552,34970,30604,30136,29708
Massachusetts,86345,73227,72266,67861,63151,62963,63656,63313,60934,59373,...,37064,36359,35714,36247,36086,33213,32241,30339,28207,26959
Michigan,60449,57700,57091,54203,52005,48801,50015,48879,46276,45994,...,32662,32267,32117,29937,30775,29472,27702,26605,24242,22965
Minnesota,71817,71920,70218,68730,67244,60907,61795,57820,52321,56090,...,33682,30981,29479,31465,30185,29087,28082,26443,23856,24436
Mississippi,42781,43441,41099,40037,35521,40850,36641,41090,38160,35078,...,22191,20570,19475,20178,19917,18166,18513,16513,16413,15430
Missouri,61726,56885,55016,59196,56630,50311,49764,45774,45817,48769,...,28682,27361,27926,27332,26497,23443,23720,21925,21939,20775
Montana,57679,59087,57075,51395,51102,44132,45088,40277,41280,40437,...,26470,26525,24827,23375,23692,22231,20474,20328,20236,19536
Nebraska,67575,59619,59374,60474,56870,53774,52196,55616,52504,49595,...,31008,30048,29549,27482,26319,25159,23268,21772,21799,21397
Nevada,61864,56550,55431,52008,49875,45369,47333,47043,51200,51434,...,35814,31908,32937,32023,29340,27983,26878,26217,23274,25776
New Hampshire,81346,74801,76260,75675,73397,71322,67819,65880,66633,64131,...,37964,39436,36032,40805,37532,34625,32338,30548,26403,25914
New Jersey,74176,72997,68468,68357,65243,61782,66692,62338,62968,64777,...,40500,39000,40049,38734,39120,36287,34241,31715,30980,27776
New Mexico,48283,47855,48451,45119,46686,42127,43424,41982,45134,43542,...,26758,25860,26540,25039,22602,19296,20758,19845,20423,20630
New York,67274,62447,61437,58005,54310,53843,47680,50636,49781,50216,...,31697,31051,31794,31591,31496,28915,26384,25025,23639,22027
North Carolina,53369,50343,53764,50797,46784,41208,41553,45206,43830,41906,...,28820,27771,26853,26329,26406,24415,22760,21861,21451,20569
North Dakota,66505,59886,60184,57415,60730,52888,55766,56361,51006,50075,...,28118,26959,25892,25264,25229,24092,22576,21508,21205,20771
Ohio,61633,59768,53985,53301,49644,46398,44375,44648,45886,45879,...,31285,31404,29790,30013,29021,27740,25773,25115,25174,23123
Oklahoma,54434,55006,50943,47077,47199,43777,48407,48455,43103,45878,...,26260,25284,25462,24384,23667,23667,21691,20948,21205,21148
Oregon,69165,64610,59135,60834,58875,56307,51775,51526,50602,49098,...,33138,31927,30190,29281,28529,27748,25038,24773,21894,21399
Pennsylvania,64524,63173,60979,60389,55173,53952,51904,49910,48314,48172,...,30995,29882,30367,29005,28690,26742,25424,23807,22877,20346
Rhode Island,62266,66390,61528,55701,58633,57812,56065,49033,51623,51634,...,33509,30432,30836,31968,30124,29842,28292,26540,24625,21612
South Carolina,57444,54971,54336,46360,44929,43749,44401,40084,41698,41101,...,26053,27578,27463,28735,23798,25533,25049,21968,20036,20309
South Dakota,59463,56894,57450,55065,53053,54453,49415,47223,45352,45826,...,27737,26259,24639,24571,24108,22294,21151,19898,18142,19409
Tennessee,56060,55240,51344,47330,43716,42499,42995,42279,38591,40517,...,25102,24318,24453,22592,22611,20856,21179,18256,17778,16782
Texas,59785,59295,58146,56473,53875,53027,51926,49047,47266,47475,...,28727,27953,27733,28228,25886,24963,24721,24162,23743,23024
Utah,77067,71319,67481,66258,63383,62967,58341,55493,56701,58491,...,35786,34251,28016,30142,30717,26313,26529,26281,25238,23057
Vermont,70066,63805,60837,59494,60708,54842,55582,51862,55928,52318,...,31065,32755,29155,31098,31295,28988,25415,24599,26000,22578
Virginia,77151,71293,66451,61486,66155,67620,64632,62616,60367,60501,...,36433,38198,36137,35073,34118,32648,29996,29715,28429,26525
Washington,79726,75418,70310,67243,59068,60106,62187,56850,56163,60392,...,35655,33900,33970,32112,31961,32327,27319,26881,24000,25017
West Virginia,50573,45392,44354,42824,39552,40241,43553,41821,42777,40490,...,22421,20271,23147,22137,21677,19353,17207,16464,15983,16843
Wisconsin,62629,63451,59817,55425,58080,55258,53079,52058,50351,51237,...,31766,33308,31133,30711,29123,29575,26369,26430,23246,20743
Wyoming,62539,57837,57829,60925,55690,55700,57512,54509,52201,52470,...,29442,30209,29050,29460,29521,26419,27590,23559,22081,23816